name: Manhunt
version: '${project.version}'
main: dev.prinke.manhunt.Manhunt
api-version: '1.20'
authors: [Prinke]
website: https://crownedinteractive.com
commands:
  manhunt:
    description: The main command for the Manhunt plugin
    aliases: [mh]
    permission: manhunt.admin
    default: op
    usage: /<command> <start|runner> [add] [player]